services:
  # Сервис Traefik (обратный прокси)
  traefik:
    image: traefik:v2.10
    container_name: kv_vopros_traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Для доступа к Dashboard Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/etc/traefik/acme.json
    networks:
      - kv_vopros_network

  # Сервис PHP-FPM (приложение)
  app:
    image: kv-vopros/app:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kv_vopros_app
    dns:
      - 8.8.8.8
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./october:/var/www/html
      - ./.env:/var/www/html/.env:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kv_vopros_network

  # Сервис Nginx (веб-сервер)
  nginx:
    image: nginx:alpine
    container_name: kv_vopros_nginx
    restart: unless-stopped
    ports:
      - "8081:80"
    volumes:
      - ./october:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - kv_vopros_network
    labels:
      - "traefik.enable=true"
      # Роутер для основного домена
      - "traefik.http.routers.kv-vopros-app.rule=Host(`kv-tyumen.ru`)"
      - "traefik.http.routers.kv-vopros-app.entrypoints=websecure"
      - "traefik.http.routers.kv-vopros-app.tls=true"
      - "traefik.http.routers.kv-vopros-app.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kv-vopros-app.service=kv-vopros-app"
      - "traefik.http.services.kv-vopros-app.loadbalancer.server.port=80"
      - "traefik.docker.network=kv_vopros_network"
      # Роутер и middleware для редиректа с www
      - "traefik.http.routers.kv-vopros-www.rule=Host(`www.kv-tyumen.ru`)"
      - "traefik.http.routers.kv-vopros-www.entrypoints=websecure"
      - "traefik.http.routers.kv-vopros-www.tls=true"
      - "traefik.http.routers.kv-vopros-www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kv-vopros-www.middlewares=redirect-to-non-www"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.regex=^https://www\\.(.*)"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.replacement=https://$${1}"
      - "traefik.http.middlewares.redirect-to-non-www.redirectregex.permanent=true"

  # Сервис базы данных MySQL
  db:
    image: mariadb:10.11 # Замена на MariaDB для лучшей совместимости с ARM (Apple M1/M2/M3)
    container_name: kv_vopros_db
    env_file:
      - ./.env
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD} # Пароль для root, если нужен
    volumes:
      - kv_vopros_db_data:/var/lib/mysql
    networks:
      - kv_vopros_network
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-p${DB_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

networks:
  kv_vopros_network:
    name: kv_vopros_network

volumes:
  kv_vopros_db_data:
    name: kv_vopros_db_data
    driver: local
